### ISSUE TITLE
Android wear

### ISSUE THREAD

**Issue by paulscott56** [MycroftAI/Mycroft-Android#14]
Let users interact with Mycroft via Android wear

**Comment by Cliabhach** [comment]
Currently being reviewed over in PR #32

**Comment by Cliabhach** [comment]
@seymour-bootay you want to assign this to yourself? Github won't let me for some reason....

**Comment by seymour-bootay** [comment]
I think @paulscott56 needs to assign it.

**Comment by paulscott56** [comment]
@seymour-bootay @Cliabhach I can't assign issues to people who are not part of the Mycroft Organisation. Sorry!
