### ISSUE TITLE
Definable reply on mobile phone on/off

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/Mycroft-Android#17]
It would be nice if there was a setting (maybe a pill switch) to be able to turn the reply on the mobile phone off.

So that only the Mycroft RPI unit replies, not it and the phone.

 Basically use the Mycroft unit on the phone/androidwear watch just as a wireless mic. Since its a bit tedious to listen to the same reply twice (once on the phone and the second time from the pi).

Cheers, thanks for the good work!

**Comment by paulscott56** [comment]
Done.  Please update and test

**Comment by marksev1** [comment]
That was really fast congrats. Can you please make an apk for me to test? Thanks.

**Comment by marksev1** [comment]
This works now as intended.
