### ISSUE TITLE
Spruce up TTSManager

### ISSUE THREAD

**Issue by Cliabhach** [MycroftAI/Mycroft-Android#2]
I want to bring the TTSManager class up a notch in quality. We'll need the following:
- javadoc for class, non-obvious methods, and important fields
  - I just like javadoc, that's all.
- some simple unit tests
  - Junit should be able to cover the existing logic with a couple simple mocks. I think.
  - never could get espresso to give useful test failure info, so I don't know how much I can do on the instrumentation side of things

@paulscott56 does that look good to you?

p.s. about that init method - any particular reason it's not a constructor?

**Comment by paulscott56** [comment]
Looks good!

No real reason for init not to be a constructor, haste to bang something out is 99% of the reason... :)

**Comment by Cliabhach** [comment]
All right, I'm on it.
