### ISSUE TITLE
Screen rotation - cards disappear

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/Mycroft-Android#22]
When I switch from portrait to landscape orientation all the cards disappear.

**Comment by seymour-bootay** [comment]
@paulscott56  you can assign this one to me (I don't see how to assign it to myself on github).  We have to save the state data on rotate.

**Comment by seymour-bootay** [comment]
used android:configChanges="orientation|screenSize" setting to ensure view is not recreated on orientation change.  We may need to revisit this as an enhancement down the road if we decide we want a different layout in landscape mode.   Also snuck in a small change, removed the line that was setting voxSwitch checked to true.  When prefs are loaded it will pick up the last state.

**Comment by marksev1** [comment]
Works, fixed. Closing :)
