### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by Cliabhach** [MycroftAI/Mycroft-Android#36]
It should definitely be OSI-approved.

**Comment by Cliabhach** [comment]
Current shortlist:
* GPLv3
* Apache 2.0

Please feel free to add a comment here or on irc if you have any opinions on the matter.

**Comment by Cliabhach** [comment]
This is in PR #44, right?

**Comment by seymour-bootay** [comment]
correct. Added license and headers.

**Comment by Cliabhach** [comment]
K, cool. What's up with all those commits? I think you might need to rebase...

**Comment by seymour-bootay** [comment]
I'm not sure.  I think it is because the only changes were adding the header comment.

**Comment by Cliabhach** [comment]
Hmm. I'm gonna merge your branch into this repo's master on my computer, see if the git history ends up with any duplicate commits.

**Comment by Cliabhach** [comment]
That worked locally just fine. But....you're merging to the wrong target! Shouldn't this be going into master?

**Comment by seymour-bootay** [comment]
D'oh.  Can I edit the PR or do I have to create a new one?  It should be going to master.  I didn't notice that because there is a feature/issues-9 branch in MycroftAI/Mycroft-Android it defaulted to that.

**Comment by Cliabhach** [comment]
You can edit the destination branch on github; the source branch can't be changed though.

**Comment by Cliabhach** [comment]
I've changed the branch for you. There's one change I'd like you to make, then feel free to merge it in.

**Comment by seymour-bootay** [comment]
Cool I made the change.  I don't have write access but @paulscott56  will merge it in when he has time.  Thanks for your help.

**Comment by Cliabhach** [comment]
Don't worry, I have write access too. Pull accepted.
