### ISSUE TITLE
Don't depend too heavily on Google Play Services

### ISSUE THREAD

**Issue by Cliabhach** [MycroftAI/Mycroft-Android#4]
I think we should wrap the Google Play Services calls in 28a46ae with the method from `GooglePlayServicesUtil` or `GoogleApiAvailability` that checks whether GMS is even installed. Otherwise we'll get a bunch of unhelpful exceptions on a device without google apps.

**Comment by paulscott56** [comment]
Removed the AppIndexing client and API, as we don't actually need it, and moved all Play Services specific code out. The PlayervicesUtil class can now be used to check for GMS, and then user can be prompted to either install it with a UserRecoverableError() or told that the functionality cannot be used
