### ISSUE TITLE
Need to add `description` to repo

### ISSUE THREAD

**Issue by BenjaminHCCarr** [MycroftAI/Mycroft-Android#47]
Can we get something like:
`Android companion app, sends commands from your Android device to your Mycroft system and returns the output as speech or other medium to the  Android device.`
added  to the `description` box of the repo.

**Comment by Cliabhach** [comment]
@BenjaminHCCarr I'm afraid I don't have permission to modify the description. @paulscott56 would you be able to do that?

**Comment by paulscott56** [comment]
Done
