### ISSUE TITLE
"Your device doesn't support speech input"

### ISSUE THREAD

**Issue by Nhoya** [MycroftAI/Mycroft-Android#61]
![image](https://user-images.githubusercontent.com/7293260/37180251-a9ef20ac-2328-11e8-97da-105ecbedbadb.png)
As you can see here I receive this error while trying to send audio, i use and LG G2 with The latest lineage OS 14.0 (Android 7.1) Can this depends from some missing service/app?

**Comment by BenjaminHCCarr** [comment]
Android 6 (I believe, it may have been 7) I don't have a good web connection to check as per app permissions for the microphone, rather than a list at install time. My best guess is that you need to toggle microphone usage on for Mycroft.

I have a Nexus 6P on LineageOS 14.1 talking to an Picroft with no issues.

I really suspect it's the per-app-usage microphone permission. Does text input work?

**Comment by Nhoya** [comment]
Well, i found the problem, [Google](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox) was missing so the intent to `RecognizerIntent.ACTION_RECOGNIZE_SPEECH` failed since i don't like so much to bloat my device, there are any known alternatives that expose this API?

**Comment by BenjaminHCCarr** [comment]
Ahh, you're running without GAPPs.

There is work on separating from Google STT, but it's currently a dependancy.

The program is `OpenSTT`:
https://github.com/MycroftAI/openstt
http://openstt.org

And is a collaboration of opensource groups including `Mozilla` and others I believe.

It is a barrier to a fully FOSS implementation and an air-gapped/non-network dependant system; however, STT requires a lot of horsepower, far more than an RPI (one of the dominant dev targets) can supply. Xeons+GPU-offloading still have trouble with real-time.

If you'd like to contribute please join us on the [Mattermost Channels](https://chat.mycroft.ai/) (a FOSS alternative to Slack)!

**Comment by Nhoya** [comment]
Sure, i'll take a look in this days, by the way i want to suggest also https://github.com/facebookresearch/wav2letter

I close the issue since is resolved

**Comment by kalexmills** [comment]
I am seeing this behavior also on a Galaxy S9...
