### ISSUE TITLE
Solved: Mycroft Android will NOT connect to Mycroft Linux 18.08.1

### ISSUE THREAD

**Issue by trekjunky** [MycroftAI/Mycroft-Android#70]
Mycroft Android worked with an earlier version of Mycroft-core, but now it will NOT connect to this version of Mycroft-core. I think it may have something to do with the Internet Port 8181 now being used by Mycroft-core when it used to be Internet Port 8000 or 8080, I don't remember which. Is there a way to change the port EITHER on Mycroft-core OR Mycroft Android? Is that the real problem? What should I look for to find the cause of the non-connectivity?

**Comment by penrods** [comment]
I don't think anything changed on the mycroft-core side with regards to this.  What kind of device are you using?  If you are using a Mark 1, make sure you have opened it up by holding down the top button, rotating to "SSH", click, then rotate to get to "ALLOW".  Under other installs make sure the appropriate firewall settings are in place.

Mycroft-core still [defaults to 8181](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/configuration/mycroft.conf#L132), but it could be overridden via your /etc/mycroft/mycroft.conf file.

**Comment by trekjunky** [comment]
I found out that my firewall on my linux machine was blocking the communication. I opened ports 5555 and 8181 on my firewall which NOW Android App connects to Mycroft. Thanks for looking into it for me

**Comment by krisgesling** [comment]
Hey it sounds like this is now working, is that right? If so we can close the issue.
