### ISSUE TITLE
Running mycroft-core server on Android phones and tablets

### ISSUE THREAD

**Issue by lyndalopez544** [MycroftAI/Mycroft-Android#89]
I wonder why shouldn't Mycroft run directly in a standalone mode on an Android device instead of connecting to a mycroft-core server?

mycroft-core with all the dependencies could be compiled and just wrapped in an Android package to be able to run on all Android-based devices.
Then, an Android Wear device could communicate to the mycroft-core server running on an Android phone or tablet.

A few things have to change in the design of mycroft-core for it to be more easily portable to Android. Since Android is Linux, there shouldn't be much difficulty running mycroft-core on Android.

**Comment by dector** [comment]
Duplicate for #10

**Comment by krisgesling** [comment]
Thanks Dector,

Also apologies for not replying sooner, this came in the day my daughter was born :smile: 

We actually have two Community developed Android projects, this "pass-through" app, and a native implementation of mycroft-core which you can see at: https://github.com/MycroftAI/MycroftCore-Android

I am sure they are keen for more contributors if anyone is interested. Just jump in and say hi on the [Android channel in Chat](https://chat.mycroft.ai/community/channels/android)

As this other project exists, I'll close this issue and let the conversation continue in the other repo and on Chat.
