### ISSUE TITLE
Don't let card text take up so much space

### ISSUE THREAD

**Issue by Cliabhach** [MycroftAI/Mycroft-Android#9]
Text added to card views take up more space than they need. Increase the right margins and use a simpler layout (if possible) so that it looks more appealing.

Also change that `notifyDataSetChanged` call to a `notifyItemChanged`/`notifyItemInserted` so we can take advantage of RecyclerView's builtin animations.

**Comment by paulscott56** [comment]
This is done as per the merge. Thanks @Cliabhach
