### ISSUE TITLE
Fix microphone input on Android 10

### ISSUE THREAD

**Issue by Hacker1245** [MycroftAI/Mycroft-Android#95]
The app says that microphone input is unavailable, possibly due to missing permissions as it does not show a permission dialog.

**Comment by skraynick** [comment]
Could be, I will have to investigate if you can't... I am a bit busy at the moment. I can look over the weekend.  Thanks for reporting.

**Comment by Saroufim** [comment]
I'm  also experiencing the issue on Android 10. I didn't happen before but then it randomly started happening.

**Comment by pritesh25** [comment]
getting toast message "Sorry, your device does not support speech input." App also not have microphone permission.

**Comment by Saroufim** [comment]
Do you have the Google search app disabled? This was the issue for me

**Comment by kleo** [comment]
I had to add the following permission to `manifests/AndroidManifests.xml` before build. The application requires Google search and TTS.

```
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
```

**Comment by skraynick** [comment]
> I had to add the following permission to `manifests/AndroidManifests.xml` before build. The application requires Google search and TTS.
> 
> ```
> <uses-permission android:name="android.permission.RECORD_AUDIO"/>
> ```

Did you want to submit a PR? If not I will... thanks.

**Comment by skraynick** [comment]
Closing issue, since PR was submitted and merged. Thanks.
